### PR TITLE
Added main table border styles

### PR DESCRIPTION
**Pull request by nadav2051**

### CODE REVIEW

**Comment by jsamr** [comment]
@nadav2051 Can you provide at least visual tests to show the result?

**Comment by nadav2051** [comment]
Sure, can you instruct me on how to create tests?

**Comment by jsamr** [comment]
Oh ; by visual test I just meant an example code and a screenshot of the result!

**Comment by jsamr** [comment]
@nadav2051 Thanks for your participation. I ended up implementing this differently as I decided to reorganize the TableStyleSpecs for release 2.0!

**Comment by nadav2051** [comment]
> @nadav2051 Thanks for your participation. I ended up implementing this differently as I decided to reorganize the TableStyleSpecs for release 2.0!

Awesome, thank you! Apologies for forgetting to submit the screenshots / example code - it totally slipped my mind

**Comment by jsamr** [comment]
@nadav2051 no worries!

**Comment by jsamr** [comment]
I also added a sketch of different style specs to easily identify which does what, see https://github.com/native-html/table-plugin/blob/master/docs/table-plugin.tablestylespecs.md

**Pull request closed without merging**
